### ISSUE TITLE
Temp dir for TemporaryStorageImpl isn't created automatically

### ISSUE THREAD

**Issue by alexbudarov** [Haulmont/jmix-localfs#2]
- create project
- attach fsfilestorage add-on
- add URI field to any entity
- add "fileStorageUpload" field to entity form
- launch application
- try to upload file

Error occurs:
```
2020-10-16 20:24:03.517 ERROR 106205 --- [io-8080-exec-10] io.jmix.ui.widget.JmixFileUpload         : Unexpected error in JmixFileUpload

com.vaadin.server.UploadException: Upload failed
	at com.vaadin.server.communication.FileUploadHandler.streamToReceiver(FileUploadHandler.java:656) ~[vaadin-server-8.9.2-5-jmix.jar:8.9.2-5-jmix]
	at com.vaadin.server.communication.FileUploadHandler.handleFileUploadValidationAndData(FileUploadHandler.java:483) ~[vaadin-server-8.9.2-5-jmix.jar:8.9.2-5-jmix]
	at com.vaadin.server.communication.FileUploadHandler.doHandleSimpleMultipartFileUpload(FileUploadHandler.java:437) ~[vaadin-server-8.9.2-5-jmix.jar:8.9.2-5-jmix]
	at com.vaadin.server.communication.FileUploadHandler.handleRequest(FileUploadHandler.java:310) ~[vaadin-server-8.9.2-5-jmix.jar:8.9.2-5-jmix]
	at com.vaadin.server.VaadinService.handleRequest(VaadinService.java:1578) ~[vaadin-server-8.9.2-5-jmix.jar:8.9.2-5-jmix]
	at com.vaadin.server.VaadinServlet.service(VaadinServlet.java:425) ~[vaadin-server-8.9.2-5-jmix.jar:8.9.2-5-jmix]
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:750) ~[javax.servlet-api-4.0.1.jar:4.0.1]
...
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1590) ~[tomcat-embed-core-9.0.36.jar:9.0.36]
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49) ~[tomcat-embed-core-9.0.36.jar:9.0.36]
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) ~[na:na]
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) ~[na:na]
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61) ~[tomcat-embed-core-9.0.36.jar:9.0.36]
	at java.base/java.lang.Thread.run(Thread.java:834) ~[na:na]
Caused by: java.lang.RuntimeException: Unable to receive file 'gaku.png' of MIME type: image/png
	at io.jmix.ui.component.impl.FileStorageUploadFieldImpl.receiveUpload(FileStorageUploadFieldImpl.java:112) ~[jmix-ui-0.1.0-SNAPSHOT.jar:na]
	at io.jmix.ui.widget.JmixFileUpload$2.getOutputStream(JmixFileUpload.java:344) ~[jmix-ui-0.1.0-SNAPSHOT.jar:na]
	at com.vaadin.server.communication.FileUploadHandler.streamToReceiver(FileUploadHandler.java:574) ~[vaadin-server-8.9.2-5-jmix.jar:8.9.2-5-jmix]
	... 74 common frames omitted
Caused by: io.jmix.core.FileStorageException: I/O error: /home/alexander/projects/ikna/.jmix/temp/607ffefb-909e-c593-49b4-7fdd93342bdf
	at io.jmix.ui.upload.TemporaryStorageImpl.createFileInternal(TemporaryStorageImpl.java:151) ~[jmix-ui-0.1.0-SNAPSHOT.jar:na]
	at io.jmix.ui.upload.TemporaryStorageImpl.createFile(TemporaryStorageImpl.java:133) ~[jmix-ui-0.1.0-SNAPSHOT.jar:na]
	at io.jmix.ui.component.impl.FileStorageUploadFieldImpl.receiveUpload(FileStorageUploadFieldImpl.java:106) ~[jmix-ui-0.1.0-SNAPSHOT.jar:na]
	... 76 common frames omitted
```

Note that there is no root cause in this exception, it is lost.

Put breakpoint, take a look what's wrong:

Looks like temp dir (.jmix/temp) isn't created automatically like it should:

![image](https://user-images.githubusercontent.com/6158807/96284380-8e5c9f80-0fee-11eb-8fb6-e070a10d8d1a.png)

**Comment by alexbudarov** [comment]
Sample project (User - photo field, User Editor)
[userphoto.zip](https://github.com/Haulmont/jmix-fsfilestorage/files/5393199/userphoto.zip)

**Comment by alexbudarov** [comment]
Also in sample project above, if upload to temporary storage fails - I get another exception in log:
```
2020-10-16 20:59:36.705 ERROR 120380 --- [nio-8080-exec-2] i.j.u.exception.DefaultExceptionHandler  : Unhandled exception

com.vaadin.server.ServerRpcManager$RpcInvocationException: Unable to invoke method fileUploaded in io.jmix.ui.widget.client.fileupload.JmixFileUploadServerRpc
	at com.vaadin.server.ServerRpcManager.applyInvocation(ServerRpcManager.java:157) ~[vaadin-server-8.9.2-5-jmix.jar:8.9.2-5-jmix]
	at com.vaadin.server.ServerRpcManager.applyInvocation(ServerRpcManager.java:115) ~[vaadin-server-8.9.2-5-jmix.jar:8.9.2-5-jmix]
	at com.vaadin.server.communication.ServerRpcHandler.handleInvocation(ServerRpcHandler.java:431) ~[vaadin-server-8.9.2-5-jmix.jar:8.9.2-5-jmix]
	at com.vaadin.server.communication.ServerRpcHandler.handleInvocations(ServerRpcHandler.java:396) ~[vaadin-server-8.9.2-5-jmix.jar:8.9.2-5-jmix]
	at com.vaadin.server.communication.ServerRpcHandler.handleRpc(ServerRpcHandler.java:260) ~[vaadin-server-8.9.2-5-jmix.jar:8.9.2-5-jmix]
	at com.vaadin.server.communication.UidlRequestHandler.synchronizedHandleRequest(UidlRequestHandler.java:82) ~[vaadin-server-8.9.2-5-jmix.jar:8.9.2-5-jmix]
	at com.vaadin.server.SynchronizedRequestHandler.handleRequest(SynchronizedRequestHandler.java:40) ~[vaadin-server-8.9.2-5-jmix.jar:8.9.2-5-jmix]
	at com.vaadin.server.VaadinService.handleRequest(VaadinService.java:1578) ~[vaadin-server-8.9.2-5-jmix.jar:8.9.2-5-jmix]
	at com.vaadin.server.VaadinServlet.service(VaadinServlet.java:425) ~[vaadin-server-8.9.2-5-jmix.jar:8.9.2-5-jmix]
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:750) ~[javax.servlet-api-4.0.1.jar:4.0.1]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231) ~[tomcat-embed-core-9.0.36.jar:9.0.36]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) ~[tomcat-embed-core-9.0.36.jar:9.0.36]
...
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49) ~[tomcat-embed-core-9.0.36.jar:9.0.36]
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) ~[na:na]
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) ~[na:na]
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61) ~[tomcat-embed-core-9.0.36.jar:9.0.36]
	at java.base/java.lang.Thread.run(Thread.java:834) ~[na:na]
Caused by: java.lang.reflect.InvocationTargetException: null
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:na]
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:na]
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:na]
	at java.base/java.lang.reflect.Method.invoke(Method.java:566) ~[na:na]
	at com.vaadin.server.ServerRpcManager.applyInvocation(ServerRpcManager.java:153) ~[vaadin-server-8.9.2-5-jmix.jar:8.9.2-5-jmix]
	... 77 common frames omitted
Caused by: com.vaadin.event.ListenerMethod$MethodException: Invocation of method uploadSucceeded in io.jmix.ui.component.impl.AbstractSingleFileUploadField$$Lambda$1186/0x0000000840da5040 failed.
	at com.vaadin.event.ListenerMethod.receiveEvent(ListenerMethod.java:516) ~[vaadin-server-8.9.2-5-jmix.jar:8.9.2-5-jmix]
	at com.vaadin.event.EventRouter.fireEvent(EventRouter.java:273) ~[vaadin-server-8.9.2-5-jmix.jar:8.9.2-5-jmix]
	at com.vaadin.event.EventRouter.fireEvent(EventRouter.java:237) ~[vaadin-server-8.9.2-5-jmix.jar:8.9.2-5-jmix]
	at com.vaadin.server.AbstractClientConnector.fireEvent(AbstractClientConnector.java:1041) ~[vaadin-server-8.9.2-5-jmix.jar:8.9.2-5-jmix]
	at io.jmix.ui.widget.JmixFileUpload.fireUploadSuccess(JmixFileUpload.java:491) ~[jmix-ui-0.1.0-SNAPSHOT.jar:na]
	at io.jmix.ui.widget.JmixFileUpload$1.fileUploaded(JmixFileUpload.java:73) ~[jmix-ui-0.1.0-SNAPSHOT.jar:na]
	... 82 common frames omitted
Caused by: java.lang.NullPointerException: null
	at java.base/java.util.concurrent.ConcurrentHashMap.get(ConcurrentHashMap.java:936) ~[na:na]
	at io.jmix.ui.upload.TemporaryStorageImpl.getFile(TemporaryStorageImpl.java:159) ~[jmix-ui-0.1.0-SNAPSHOT.jar:na]
	at io.jmix.ui.upload.TemporaryStorageImpl.putFileIntoStorage(TemporaryStorageImpl.java:193) ~[jmix-ui-0.1.0-SNAPSHOT.jar:na]
	at io.jmix.ui.component.impl.FileStorageUploadFieldImpl.saveFile(FileStorageUploadFieldImpl.java:124) ~[jmix-ui-0.1.0-SNAPSHOT.jar:na]
	at io.jmix.ui.component.impl.FileStorageUploadFieldImpl.onUploadSucceeded(FileStorageUploadFieldImpl.java:144) ~[jmix-ui-0.1.0-SNAPSHOT.jar:na]
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:na]
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:na]
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:na]
	at java.base/java.lang.reflect.Method.invoke(Method.java:566) ~[na:na]
	at com.vaadin.event.ListenerMethod.receiveEvent(ListenerMethod.java:496) ~[vaadin-server-8.9.2-5-jmix.jar:8.9.2-5-jmix]
	... 87 common frames omitted


```

**Comment by glebshalyganov** [comment]
Fixed in https://github.com/Haulmont/jmix-ui/issues/197
